config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :users do
    resources :shows do
      member do
        get 'show_access'
      end
    end
  end
  get 'pages/select', to: 'pages#select'
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/show.rb
class Show < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  after_commit :add_default_image, on: [:create, :update]


  private

  def add_default_image
    unless image.attached?
      self.image.attach(io: File.open(Rails.root.join("app", "assets", "images", "default.jpg")), filename: 'default.jpg' , content_type: "image/jpg")
    end
  end

end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
  before_action :set_show, only: [:show, :edit, :update, :destroy, :show_access]
  before_action :authenticate_user!
  # GET /shows
  # GET /shows.json
  def index
    @shows = Show.all
    @today_shows = Show.where("DATE(date)=?", Date.today)
  end

  # GET /shows/1
  # GET /shows/1.json
  def show
  end

  # GET /shows/new
  def new
    @show = Show.new
  end

  # GET /shows/1/edit
  def edit
  end

  # POST /shows
  # POST /shows.json
  def create
    @show = Show.new(show_params)
    @show.user = current_user
    @show.meeting_id = SecureRandom.hex(10)
    respond_to do |format|
      if @show.save
        format.html { redirect_to user_shows_path(current_user), notice: 'Show was successfully created.' }
        format.json { render :show, status: :created, location: @show }
      else
        format.html { render :new }
        format.json { render json: @show.errors, status: :unprocessable_entity }
      end
    end
  end

  def show_access
    url_base = "https://tarimavirtual3.kodim.tech/bigbluebutton/api/"
    room_id = @show.meeting_id
    full_names = "#{current_user.email}"
    attendee_pw = 'ap'
    moderator_pw = 'mp'

    string_to_checksum = "getMeetingInfo?meetingID=#{room_id}n2xZ9tJAi870q7ns9xtPuogGkyAALpJ0HGBhGXbzhPM"
    get_checksum = Digest::SHA1.hexdigest string_to_checksum
    response_url = HTTParty.get("#{url_base}getMeetingInfo?meetingID=#{room_id}&checksum=#{get_checksum}")

    data_response = response_url.parsed_response.to_json
    json = JSON.parse(data_response)

    if json['response']['returncode'] == 'FAILED'
      
      create_meeting(url_base, room_id, moderator_pw, attendee_pw)
      
      string_to_join = "joinfullName=#{full_names}&password=#{moderator_pw}&meetingID=#{room_id}&redirect=truen2xZ9tJAi870q7ns9xtPuogGkyAALpJ0HGBhGXbzhPM"
      join_checksum = Digest::SHA1.hexdigest string_to_join
      redirect_to "#{url_base}join?fullName=#{full_names}&password=#{moderator_pw}&meetingID=#{room_id}&redirect=true&checksum=#{join_checksum}"
    elsif json['response']['returncode'] == 'SUCCESS'
      string_to_join = "joinfullName=#{full_names}&password=#{moderator_pw}&meetingID=#{room_id}&redirect=truen2xZ9tJAi870q7ns9xtPuogGkyAALpJ0HGBhGXbzhPM"
      join_checksum = Digest::SHA1.hexdigest string_to_join
      redirect_to "#{url_base}join?fullName=#{full_names}&password=#{moderator_pw}&meetingID=#{room_id}&redirect=true&checksum=#{join_checksum}"
    end
  end

  def create_meeting(url_base, room_id, moderator_pw, attendee_pw)
    string_to_create = "createmeetingID=#{room_id}&moderatorPW=#{moderator_pw}&attendeePW=#{attendee_pw}n2xZ9tJAi870q7ns9xtPuogGkyAALpJ0HGBhGXbzhPM"
    create_checksum = Digest::SHA1.hexdigest string_to_create
    create_response = HTTParty.post("#{url_base}create?meetingID=#{room_id}&moderatorPW=#{moderator_pw}&attendeePW=#{attendee_pw}&checksum=#{create_checksum}")
  end

  # PATCH/PUT /shows/1
  # PATCH/PUT /shows/1.json
  def update
    respond_to do |format|
      if @show.update(show_params)
        format.html { redirect_to @show, notice: 'Show was successfully updated.' }
        format.json { render :show, status: :ok, location: @show }
      else
        format.html { render :edit }
        format.json { render json: @show.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shows/1
  # DELETE /shows/1.json
  def destroy
    @show.destroy
    respond_to do |format|
      format.html { redirect_to shows_url, notice: 'Show was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_show
      @show = Show.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def show_params
      params.require(:show).permit(:image, :title, :content, :date, :time,  :duration, :user_id)
    end
end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/views/shows/_form.html.erb
<style>
  .file-upload-button {
    display: none;
  }
</style>
<div class="container">
<div class="row">
<div class="offset-3 col-md-6">
<h1 class="pb-3">Publicar nuevo show</h1>
<%= form_with(model: [current_user, show], local: true) do |form| %>
  <% if show.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(show.errors.count, "error") %> prohibited this show from being saved:</h2>

      <ul>
        <% show.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.file_field :image, class:'form-control', style:'' %>
  </div>

  <div class="form-group">
    <%= form.text_field :title, class:'form-control', placeholder:'Titulo del show'  %>
  </div>

  <div class="form-group">
    <%= form.text_area :content, class:'form-control', placeholder: 'Descripción' %>
  </div>

  <div class="form-group">
    <%= form.date_select :date, class:'form-control'  %>
  </div>

  <div class="form-group">
    <%= form.time_select :time, class:'form-control'  %>
  </div>

  <div class="form-group">
    <%= form.number_field :duration, class:'form-control', placeholder: 'Duracion'  %>
  </div>


  <div class="form-group">
    <%= form.submit(class:'btn btn-block btn-secondary' )%>
  </div>
<% end %>

<%= link_to 'Volver', user_shows_path(current_user)%>
</div>
</div>
</div>

app/views/shows/edit.html.erb
<h1>Editing Show</h1>

<%= render 'form', show: @show %>

<%= link_to 'Show', @show %> |
<%= link_to 'Back', shows_path %>

app/views/shows/index.html.erb
<style>
.main {
  padding:50px;
}

.carusell {
  padding-top: 30px;
}

.card-img-overlay {
    display:none
}

a {
  text-decoration:none !important;
}
</style>

<div class="main">
<h1>Mis presentaciones</h1>

<%= link_to 'Nuevo Show', new_user_show_path(current_user), class:'float-right btn btn-sm btn-primary' %>
<div class="carusell">
    <h3 class="pb-2">Categoria</h3>
    <div class="px-3 row">
        <% current_user.shows.each do |show| %>
        <a href="<%= show_access_user_show_path(id: show.id) %>">
        <div class="card card-box rounded-0 border-0" id="<%= show.id %>">
            <%= image_tag show.image, class:' h-100', style:"object-fit: cover"%>
            <div class="card-img-overlay to-hover" id="text<%= show.id %>">
                <h5 class="card-title"><%= show.title %></h5>
                <p class="card-text"><%= show.content %></p>
                <p class="card-text"><%= show.date %><%= show.time %></p>
            </div>
        </div>
        </a>
        <% end %>
    </div>
</div>
</div>

<script>
    $(".card").hover(function(){
        var id_card = $(this).attr('id');
        var id_text  =  'text' + id_card ;
        document.getElementById(id_text).style.background = "white";
        document.getElementById(id_text).style.opacity = .8;
        document.getElementById(id_text).style.display = "block";
    }, function(){
        var id_card = $(this).attr('id');
        var id_text  =  'text' + id_card ;
        document.getElementById(id_text).style.display = "none";
    })
</script>

app/views/shows/new.html.erb
<%= render 'form', show: @show %>

app/views/shows/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Image:</strong>
  <%= @show.image %>
</p>

<p>
  <strong>Title:</strong>
  <%= @show.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @show.content %>
</p>

<p>
  <strong>Date:</strong>
  <%= @show.date %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @show.duration %>
</p>

<p>
  <strong>User:</strong>
  <%= @show.user_id %>
</p>